name: flaury_mobile
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_staggered_grid_view: ^0.7.0
  hooks_riverpod: ^2.4.9
  flutter_spinkit:
  smooth_page_indicator:
  flutter_svg: ^2.0.10+1
  flutter_animate:
  device_preview: ^1.1.0
  dio: ^5.5.0+1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/illustrations/
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: font/Montserrat-VariableFont_wght.ttf
          weight: 700
        - asset: font/Montserrat-VariableFont_wght.ttf
          weight: 500
        - asset: font/Montserrat-VariableFont_wght.ttf
          weight: 400