name: flaury_mobile
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.4.9
  flutter_spinkit:
  flutter_screenutil:
  smooth_page_indicator:
    


 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/illustrations/
    - assets/icons/

  fonts:
    - family: Figtree
      fonts:
        - asset: font/Figtree-Medium.ttf
          weight: 600
        - asset: font/Figtree-Regular.ttf
          weight: 500
        - asset: font/Figtree-SemiBold.ttf
          weight: 400

          
 
  